<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0" PrivateAssets="All" />
    <PackageReference Include="Google.Protobuf" Version="3.36.2" />
    <Protobuf Include="../protocol/runner.proto" GrpcServices="Client" />
    <Content Include="../database/schema.sqlite.sql" Link="schema.sqlite.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
